export default {
  // token request home
  ACTION_FETCH_TOKEN: "ACTION_FETCH_TOKEN",

  ACTION_API_ERROR_SUCCESS: "ACTION_API_ERROR_SUCCESS",
  ACTION_API_ERROR_REQUEST: "ACTION_API_ERROR_REQUEST",

  ACTION_GET_ACCESS_TOKEN_REQUEST: "ACTION_GET_ACCESS_TOKEN_REQUEST",
  ACTION_GET_ACCESS_TOKEN_SUCCESS: "ACTION_GET_ACCESS_TOKEN_SUCCESS",
  ACTION_GET_ACCESS_TOKEN_FAILURE: "ACTION_GET_ACCESS_TOKEN_FAILURE",
};
