export default {

  ACTION_API_ERROR_SUCCESS: "ACTION_API_ERROR_SUCCESS",
  ACTION_API_ERROR_REQUEST: "ACTION_API_ERROR_REQUEST",

  ACTION_GET_ACCESS_TOKEN_REQUEST: "ACTION_GET_ACCESS_TOKEN_REQUEST",
  ACTION_GET_ACCESS_TOKEN_SUCCESS: "ACTION_GET_ACCESS_TOKEN_SUCCESS",
  ACTION_GET_ACCESS_TOKEN_FAILURE: "ACTION_GET_ACCESS_TOKEN_FAILURE",

  ACTION_GET_SIGN_UP_REQUEST: "ACTION_GET_SIGN_UP_REQUEST",
  ACTION_GET_SIGN_UP_SUCCESS: "ACTION_GET_SIGN_UP_SUCCESS",
  ACTION_GET_SIGN_UP_FAILURE: "ACTION_GET_SIGN_UP_FAILURE",

  ACTION_FORGOT_PASSWORD_REQUEST: "ACTION_FORGOT_PASSWORD_REQUEST",
  ACTION_FORGOT_PASSWORD_SUCCESS: "ACTION_FORGOT_PASSWORD_SUCCESS",
  ACTION_FORGOT_PASSWORD_FAILURE: "ACTION_FORGOT_PASSWORD_FAILURE",

  
  ACTION_RESET_PASSWORD_REQUEST: "ACTION_RESET_PASSWORD_REQUEST",
  ACTION_RESET_PASSWORD_SUCCESS: "ACTION_RESET_PASSWORD_SUCCESS",
  ACTION_RESET_PASSWORD_FAILURE: "ACTION_RESET_PASSWORD_FAILURE",

  ACTION_GET_QR_CODE_REQUEST : "ACTION_GET_QR_CODE_REQUEST",
  ACTION_GET_QR_CODE_SUCCESS : "ACTION_GET_QR_CODE_SUCCESS",
  ACTION_GET_QR_CODE_FAILURE : 'ACTION_GET_QR_CODE_FAILURE',

  ACTION_GET_PROFILE_REQUEST: "ACTION_GET_PROFILE_REQUEST",
  ACTION_GET_PROFILE_SUCCESS: "ACTION_GET_PROFILE_SUCCESS",
  ACTION_GET_PROFILE_FAILURE: "ACTION_GET_PROFILE_FAILURE",


  ACTION_UPDATE_PROFILE_REQUEST: "ACTION_UPDATE_PROFILE_REQUEST",
  ACTION_UPDATE_PROFILE_SUCCESS: "ACTION_UPDATE_PROFILE_SUCCESS",
  ACTION_UPDATE_PROFILE_FAILURE: "ACTION_UPDATE_PROFILE_FAILURE",


  ACTION_SET_MARKED_DATES : "ACTION_SET_MARKED_DATES",

  ACTION_GET_ROASTER_DATE_REQUEST : "ACTION_GET_DATE_REQUEST",
  ACTION_GET_ROASTER_DATE_SUCCESS : "ACTION_GET_DATE_SUCCESS",
  ACTION_GET_ROASTER_DATE_FAILURE : "ACTION_GET_DATE_FAILURE",

  ACTION_GET_SELECT_ROASETER_DATE_DATA_REQUEST : 'ACTION_GET_SELECT_ROASETER_DATE_REQUEST',
  ACTION_GET_SELECT_ROASETER_DATE_DATA_SUCCESS : 'ACTION_GET_SELECT_ROASETER_DATE_DATA_SUCCESS',
  ACTION_GET_SELECT_ROASETER_DATE_DATA_FAILURE : 'ACTION_GET_SELECT_ROASETER_DATE_DATA_FAILURE',
};
