const API_PATHS = {
  FETCH_USER_DETAILS: 'user/me',
  SYNC_FETCH_USER_DETAILS: 'user/sync',
  FETCH_QUALIFICATIONS: '/qualification',
  SYNC_FETCH_QUALIFICATIONS: '/qualification/sync',
  FETCH_SPECIALITIES: '/specialisation',
  SYNC_FETCH_SPECIALITIES: '/specialisation/sync',
  FETCH_LEAVES: '/leave',
  SYNC_FETCH_LEAVES: '/leave/sync',
  FETCH_LEAVE_TYPES: '/leave/types',
  FETCH_HOLIDAYS: '/holiday',
  SYNC_FETCH_HOLIDAYS: '/holiday/sync',
  MTP_CALENDAR: 'mtp/staffpositionId/calendar/month',
  MTP_ROLLOVER:
    'mtp/rolloverplan/staffPositionId?month=monthVal&year=yearVal&rolloverType=rolloverTypeData',
  MTP_ROLLOVER_OF_MR_BY_REPORTING_MANAGER:
    'mtp/rolloverplan/staffPositionId?month=monthVal&year=yearVal&reportingStaffPositionId=reportingStaffPositionVal&rolloverType=rolloverTypeData',
  GET_MISSED_CALLS:
    'dailyplanactivity/staffPositionId/month/missedCall/parties',
  ADD_TODAY_PLAN: 'dailyplanactivity/adhocplan',
  GET_SEARCH_DOCTORS: 'party/searchpartybyname',
  GET_TASKS: 'taskinfo/opentask',
  GET_PRODUCT: '/product/partyproduct',
  GET_TIMELINE: 'mtp/timeline/visit',
  GET_DOCTOR_LIST: '/party/partybyspid',
  GET_ALL_EDIT: '/nfa/Edit',
  GET_EDETAILED_LIST: '/edetailing/listforparties',
  TOUR_PLAN_STATUS: 'stp/tourplan/status',
  SWAP: 'mtp/staffPositionId/patch/swap',
  SHUFFLE: 'mtp/staffPositionId/patch/shuffle',
  ACTIVITY:
    'activity?divisionId=divId&getAll=getAllParam&isForMRs=isForMRsParam',
  ACTIVITY_TYPE: 'activitytype?divisionId=divId',
  GET_MY_PERFORMANCE_MASTER_DATA: 'performance/filter',
  CONTACT_DETAILS: 'contactdetail',
  GET_MTP_MISSED_CALLS:
    'mtp/missedparties/staffPositionId?month=monthVal&year=yearVal',
  SUBMIT_PRESENTATION_DATA: '/edetailing',
  SUBMIT_CATALOG_ANALYTICS: '/edetailing/cataloganalytics',
  PRODUCT_CATALOG: 'productcatalog',
  SYNC_PRODUCT_CATALOG: 'productcatalog/sync',
  SAVE_PER_DAY_PLAN: 'dailyplanactivity',
  SUBMIT_DCR: 'dcr',
  RCPA_FETCH_COMPETITORS: 'competitor',
  RCPA_SUBMIT: 'rcpa',
  SUBMIT_MTP: 'mtp/submit',
  tokenRegistration: 'notification/registerdevicetoken',
  COMPLAINCE_MTP_MONTHLY:
    '/compliance/monthlytourplan/staffPositionId/month?year=yearVal&month=monthVal',
  COMPLAINCE_DAILY:
    'compliance/standardtourplan/staffPositionId/daily?week=weekVal&weekday=weekdayVal',
  COMPLAINCE_MONTHLY: 'compliance/standardtourplan/staffPositionId/month',
  COMPLAINCE_FLM_MONTHLY:
    '/compliance/monthlytourplan/flm/staffPositionId/month?year=yearVal&month=monthVal',
  GET_MTP_VISIT_PROGRESS:
    'mtp/staffPositionId/visit/progress?month=monthVal&year=yearVal',
  GET_CALL_REPORTINGS:
    'dailycallreport?StaffPositionId=staffPositionIdVal&RoleId=roleIdVal&FromDate=fromDateVal&ToDate=toDateVal&DailyCallReportStatusId=callReportStatusIdVal',
  POST_CALL_REPORTINGS: 'dcr/submit/dailycallreport',
  NOTIFICATION: 'notification',
  SYNC_NOTIFICATION: 'notification/sync',
  NOTIFICATION_MARKREAD: 'notification/markasread',
  GET_FLM_INFO: 'mtp/allMTPStatus',
  GET_VISIT: 'dailyplanactivity/visits',
  GET_CHEMIST_DOCTOR: 'party/doctorchemists',
  TOTAL_BRANDS: 'party/brandsold',
  SUBMIT_REOMMENDATION_AND_APPROVAL: 'mtp/review',
  SAVE_FLM_MTP: 'mtp/jointfieldvisit',
  GET_CHEMIST_MORE_ACTION: 'sku?divisionId=divId',
  GET_DAILY_PLAN_STATUS:
    'mtp/dailyplanstatus?staffPositionId=staffPositionIdVal&month=monthVal&year=yearVal',
  GET_MR_MTP_STATUS: 'mtp/mrmtpstatus/flmStaffPositionId/monthVal/yearVal',
  SUBMIT_PURCHASE_ORDER_DATA: 'partymoreaction/purchaseorderbooking',
  SUBMIT_NONMOVING_ORDER_DATA: 'partymoreaction/nonmovingnearexpiry',
  GET_NONMOVING_ORDER_LIST:
    'partymoreaction/nonmovingnearexpiry?StaffPositionId=staffPositionIdVal&PartyId=partyIdVal&ActivityDate=activityDateVal',
  GET_PURCHASE_ORDER_LIST:
    'partymoreaction/purchaseorderbooking?StaffPositionId=staffPositionIdVal&PartyId=partyIdVal&ActivityDate=activityDateVal',
  UPCOMING_EVENTS: 'party/upcomingevents',
  GET_USER_APP_SETTINGS: '/user/appsettings',
  GET_SUBORDINATES: 'staff/getsubordinates',
  GET_All_SUBORDINATES: 'staff/getallsubordinates',
  SUBMIT_CHEMIST_END_VISIT: 'partymoreaction/endvisit',
  GET_END_VISIT_DATA_OPEN_ORDERS:
    'partymoreaction/endvisit?StaffPositionId=staffPositionIdVal&PartyId=partyIdValue&ActivityDate=activityDateVal',
  GET_FLM_MTP_SUMMARY:
    'mtp/plansummary/staffPositionId?day=dayVal&month=monthVal&year=yearVal',
  GET_ITEMS: 'item',
  WORKING_DAY: 'stp/workingday',
  GET_ALL_DOCTORS: 'party/partybyspid',
  POST_ALL_DOCTORS: 'party/add/doctorchemistmap',
  GET_CORE_PARTIES: 'party/coreparties',
  GET_ADOPTED_PARTIES: 'party/adoptedparties',
  GET_CHEMIST_VISIT_STATUS:
    'partymoreaction/visitstatus?StaffPositionId=staffPositionIdVal&PartyId=partyIdValue&ActivityDate=activityDateVal',
  RCPA_PERFORMANCE_CHEMIST: 'rcpa/partywise/brand/performance',
  DCR_INFO: 'expense/dcrinfo',
  DCR_GET_TADA: 'expense/calculate',
  DCR_SAVE_EXPENSE: 'expense/submitdcrandexpense',
  DCR_GET_READ_EXPENSE: 'expense',
  RCPA_DONE_STATUS_LIMIT_DAYS: 'rcpa/donestatus/limitdays',
  DOCTOR_UNIVERSE_MASTER: 'master',
  DOCTOR_UNIVERSE_SEARCH: 'doctor/universe/staffPositionId/search',
  GET_SAMPLES: 'sku/withinventory',
  GET_LOCATION: 'geolocation/staffstation',
  GET_OTHER_LOCATION: 'geolocation/staffstation/other',
  GET_SENIOR: 'staff/getreporters',
  GET_PRODUCT_LIST: 'product',
  GET_DCR_DATA: 'taskinfo/parties/opentask',
  DOCTOR_UNIVERSE_DOCTOR_INFO:
    'doctor/universe/staffPositionId/doctordetail/doctorId/addedInMSL',
  DOCTOR_UNIVERSE_MASTER_CHEMIST: 'master/area/staffPositionId/chemist',
  DOCTOR_UNIVERSE_DETAILS_SUBMIT: 'doctor/universe/staffPositionId/patchName',
  DOCTOR_UNIVERSE_DETAILS_EDIT: 'doctor/universe/staffPositionId/patchName',
  DOCTOR_UNIVERSE_MOTHERBRAND:
    'master/motherbrand/staffPositionId/submotherbrand',
  MEDIUM: 'lookup',
  SUBMIT_REJECTION_AND_APPROVAL: 'doctor/reviewparty',
  SUBMIT_NUDGES: '/nudge/add/nudgefeedback',
  POST_NON_FIELD_ACTIVITY: 'dailycallreport/adhocplan/nonfieldactivity',
  POST_DATA_NON_FIELD_ACTIVITY: 'nonfieldactivity',
  GET_DOCTOR_UNIVERSE_MR_LIST: 'doctor/universe/staffPositionId/mrlist',
  GET_PRIORITY_PRODUCT: 'product/partypriorityproduct',
  PARTY_SEARCH: 'dailyplanactivity/search/staffPositionId/blankday',
  SUBMIT_SLIDE_SELECTION: 'edetailing/plan',
  DCR_HISTORY: 'dcr/previous/monthlysupport',
  GET_RCPA_HISTORY: 'rcpa',
  DOCTOR_UNIVERSE_CONFIGURATION: 'doctor/universe/configuration',
  GET_OPEN_TASK: 'taskinfo/todaysdueopentasks',
  PARTY_BY_SPID: '/party/partybyspid',
  GET_NUDGE: '/nudge',
  NUDGE_MASTERDATA_PULL: '/nudge/pull',
  NUDGE_SYNC: '/nudge/sync',
  NUDGE_DATA: '/nudge',
  NUDGE_FEEDBACK: '/nudge/userfeedback',
  DOCTOR_UNIVERSE_COUNT: 'doctor/universe/count',
  DELETE_PARTY_FLM: '/dailycallreport/jointvisit/decline',
  DELETE_PARTY_ADHOC: 'dailyplanactivity/remove',
  REMOVE_NFA_FROM_DAILY_PLAN: 'dailyplanactivity/remove',
  COMPLAINCE_SLM_MONTHLY:
    '/compliance/monthlytourplan/slm/staffPositionId/month?year=yearVal&month=monthVal',
  GET_UNLOCK_LIST: 'dcrunlock/unlockrequest?staffpositionId=staffpositionIdVal',
  TIMESLOT_SYNC: '/timeslot/sync',
  TIMESLOT_DATA: '/timeslot',
  PARTY_PLANNED_VISITS: 'party/partiesplannedvisits',
  UNLOCK_REASON: 'dcrunlock/reason',
  RAISE_UNLOCK_REQUEST: 'dcrunlock/raiseunlockrequest',
  GET_MY_PLAN_SUBORDINATES: '/dailycallreport/subordinatedailyplanstatus',
  UPDATE_UNLOCK_REQUEST: 'dcrunlock/updatedcrunlockrequest',
  POST_TABLEAU: 'tableau/authentication',
  IMPORT_DCR: 'manageractivity/import',
  GET_GSP_DOCTORL_LIST: 'gsp/',
  GET_GSP_SEGMENTS: 'gsp/staffPositionId/segments/year',
  GET_GSP_SEGMENT_BRANDS: 'gsp/staffPositionId/segmentId/brands/forYear/isRest',
  GET_GSP_BRAND_DOCTORS:
    'gsp/staffPositionId/brandId/doctors/year/financialYear',
  MANAGER_JOURNEY_DCR: 'manageractivity',
  RESET_MTP: 'mtp/reset/staffPositionId',
  SUBMIT_GSP_YEARLY_PLAN: 'gsp/staffPositionId/yearlylock/financialyear/year',
  GSP_AUTO_CALCULATE_REST: 'gsp/restsegmentbrands',
  GSP_UPDATE_REST_BRANDS: 'gsp/restsegmentbrands',
  GSP_SAVE_REMAINING_BRANDS: 'gsp/remainingsegmentbrands',
  GET_LEAVES: 'mtp/holidayandleave/year/month',
  CHECK_HOLIDAYS_FILLED:
    'holiday/checkifholidaysfilled?userId=userIdData&years=yearToPass',
  DELETE_PARTY_PLANNED: 'dailyplanactivity/removedcr',
  DCR_FILLED_DATE: 'staff/config',
  GSP_MANAGER_ASPIRATION: 'gsp/managers/gettotalaspirationformanagers',
  GSP_MANAGER_SEGMENTS_YEARLY: 'gsp/managers/getsegmentbrandsformanagersyearly',
  GSP_MANAGER_SEGMENTS_MONTHLY:
    'gsp/managers/getsegmentbrandsformanagersmonthly',
  GSP_MANAGER_STATUS: 'gsp/managers/getsubordinatedetailsdata',
  GSP_MANAGER_STATUS_SEGMENTS_YEARLY:
    'gsp/managers/getsubordinatedetailsdatayearlybystaffpositionid',
  GSP_MANAGER_STATUS_SEGMENTS_MONTHLY:
    'gsp/managers/getsubordinatedetailsdatamonthlybystaffpositionid',
  GSP_MANAGER_STATUS_REJECT: 'gsp/managers/rejectmrgspbymanager',
  GSP_MANAGER_STATUS_SUBMIT: 'gsp/managers/submitmrgspbymanager',
};

export default API_PATHS;
